import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2E2E2E',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '100%',
    maxHeight: '100%',
    paddingBottom: 30,
  },
  separator: {
    backgroundColor: '#FFF',
    height: 1,
  },
  inputAgencia: {
    alignSelf: 'flex-start',
    width: '40%',
    height: 30,
    borderBottomColor: '#A74F4F',
    borderBottomWidth: 1,
    marginBottom: 20,
    fontSize: 15,
    color: '#FFF',
    opacity: 0.7,
    marginLeft: 180,
  },
  inputConta: {
    width: '44%',
    height: 30,
    borderBottomColor: '#A74F4F',
    borderBottomWidth: 1,
    alignSelf: 'flex-start',
    fontSize: 18,
    color: '#FFF',
    marginLeft: 20,
    opacity: 0.7,
  },
  image: {
    marginTop: 40,
    alignSelf: 'center',
    width: 150,
    height: 150,
    alignContent: 'flex-start',
    borderRadius: 100,
    resizeMode: 'contain',
  },
  button: {
    width: '90%',
    height: 50,
    backgroundColor: '#D52247',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    resizeMode: 'contain',
  },
  contaAgencia: {
    flex: 1,
    flexDirection: 'row',
  },
  textButton: {
    fontFamily: 'Montserrat_100Thin',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 20,
    lineHeight: 21,
    color: '#FFFFFF',
  },
  text: {
    fontSize: 12,
    lineHeight: 14,
    marginLeft: 20,
    color: '#B87979',
    alignSelf: 'flex-start',
  },
  containerInputs: {
    flexDirection: 'row',
  },
  inputs: {
    width: '90%',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  textInputAgencia: {
    fontSize: 10,
    lineHeight: 14,
    marginLeft: 40,
    color: '#B87979',
    alignSelf: 'center',
  },
  iconEdit: {
    alignSelf: 'flex-end',
    marginRight: 30,
    marginTop: 10,
  },
  inputLogin: {
    width: '80%',
    height: 50,
    borderBottomColor: '#FFF',
    borderBottomWidth: 1,
    marginTop: 30,
    fontSize: 20,
    opacity: 0.7,
    color: '#FFF',
  },
  imageLogin: {
    alignSelf: 'center',
    width: 200,
    height: 200,
    alignContent: 'flex-start',
  },
  buttonLogin: {
    marginTop: 20,
    width: '80%',
    height: 50,
    backgroundColor: '#D52247',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrol: {
    backgroundColor: '#2E2E2E',
    paddingTop: '10%',
  },
  editImage: {
    color: '#FFF',
    alignSelf: 'center',
    marginLeft: '2%',
    marginTop: 10,
    opacity: 0.75,
    fontFamily: 'Montserrat_100Thin',
  },
  facaLogin: {
    color: '#fff',
    fontSize: 16,
    alignSelf: 'flex-start',
    marginTop: 20,
    marginBottom: 20,
    marginLeft: '5%',
    fontFamily: 'Montserrat_100Thin',
  },
});

export default styles;
